// Copied from origin/tabs:src/components/Tabs/constants.ts (demo data, not exported by @inventive-ui/components/Tabs)
export const tabData = [
  {
    id: "1",
    label: "Tabs",
    content: "tab content",
    loading: false,
    disabled: false,
    helperText: "",
    helperTextPosition: "bottom",
  },
  {
    id: "2",
    label: "Tabs",
    content: "tab content",
    loading: false,
    disabled: false,
    helperText: "",
    helperTextPosition: "bottom",
  },
  {
    id: "3",
    label: "Tabs",
    content: "tab content",
    loading: false,
    disabled: false,
    helperText: "",
    helperTextPosition: "bottom",
  },
  {
    id: "4",
    label: "Tabs",
    content: "tab content",
    loading: false,
    disabled: false,
    helperText: "",
    helperTextPosition: "bottom",
  },
];

export const tabSmallData = [
  {
    id: "1",
    label: "Tabs",
    content: "tab content",
    loading: false,
    disabled: false,
    helperText: "",
    helperTextPosition: "bottom",
  },
  {
    id: "2",
    label: "Tabs",
    content: "tab content",
    loading: false,
    disabled: false,
    helperText: "",
    helperTextPosition: "bottom",
  },
];

export const tabBigData = [
  {
    id: "1",
    label: "Tabs",
    content: "tab content",
    loading: false,
    disabled: false,
    helperText: "",
    helperTextPosition: "bottom",
  },
  {
    id: "2",
    label: "Tabs",
    content: "tab content",
    loading: false,
    disabled: false,
    helperText: "",
    helperTextPosition: "bottom",
  },
  {
    id: "3",
    label: "Tabs",
    content: "tab content",
    loading: false,
    disabled: false,
    helperText: "",
    helperTextPosition: "bottom",
  },
  {
    id: "4",
    label: "Tabs",
    content: "tab content",
    loading: false,
    disabled: false,
    helperText: "",
    helperTextPosition: "bottom",
  },
  {
    id: "5",
    label: "Tabs",
    content: "tab content",
    loading: false,
    disabled: false,
    helperText: "",
    helperTextPosition: "bottom",
  },
  {
    id: "6",
    label: "Tabs",
    content: "tab content",
    loading: false,
    disabled: false,
    helperText: "",
    helperTextPosition: "bottom",
  },
  {
    id: "7",
    label: "Tabs",
    content: "tab content",
    loading: false,
    disabled: false,
    helperText: "",
    helperTextPosition: "bottom",
  },
  {
    id: "8",
    label: "Tabs",
    content: "tab content",
    loading: false,
    disabled: false,
    helperText: "",
    helperTextPosition: "bottom",
  },
  {
    id: "9",
    label: "Tabs",
    content: "tab content",
    loading: false,
    disabled: false,
    helperText: "",
    helperTextPosition: "bottom",
  },
  {
    id: "10",
    label: "Tabs",
    content: "tab content",
    loading: false,
    disabled: false,
    helperText: "",
    helperTextPosition: "bottom",
  },
  {
    id: "11",
    label: "Tabs",
    content: "tab content",
    loading: false,
    disabled: false,
    helperText: "",
    helperTextPosition: "bottom",
  },
];

export const TabsWithoutIcon = [
  {
    id: "1",
    label: "Tabs",
    content: "tab content",
    loading: false,
    disabled: false,
    helperText: "",
    helperTextPosition: "bottom",
  },
  {
    id: "2",
    label: "Tabs",
    content: "tab content",
    loading: false,
    disabled: false,
    helperText: "",
    helperTextPosition: "bottom",
  },
  {
    id: "3",
    label: "Tabs",
    content: "tab content",
    loading: false,
    disabled: false,
    helperText: "",
    helperTextPosition: "bottom",
  },
  {
    id: "4",
    label: "Tabs",
    content: "tab content",
    loading: false,
    disabled: false,
    helperText: "",
    helperTextPosition: "bottom",
  },
];
