// Copied from origin/avatar:src/components/Avatar/stories/avatar-story-controls.ts (only the constant the Showcase story uses)
export const AVATAR_COLOR_OPTIONS = [
  "brand",
  "neutral",
  "grey",
  "orange",
  "yellow",
  "green",
  "emerald",
  "teal",
  "cyan",
  "sky",
  "blue",
  "indigo",
  "violet",
  "purple",
  "fuchsia",
  "pink",
  "rose",
  "red",
  "amber",
  "success",
  "warning",
  "danger",
  "info",
  "slate",
  "zinc",
  "stone",
  "white",
  "black",
] as const;
